variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:20-alpine
  only:
    - main
  script:
    - yarn
    - yarn test
  cache:
    paths:
      - node_modules

build:
  stage: build
  image: node:20-alpine
  only:
    - main
  script:
    - yarn build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - .next
      - build

docker-build:
  image: docker:latest
  stage: deploy
  only:
    - main
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_ID" -p "$DOCKER_HUB_PASSWORD"
  script:
    - docker build -t $DOCKER_HUB_ID/$CI_PROJECT_NAME:latest --tag $DOCKER_HUB_ID/$CI_PROJECT_NAME:latest .
    - docker push $DOCKER_HUB_ID/$CI_PROJECT_NAME:latest
